// <auto-generated />
using System;
using AlxorCore.Reservas.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Reservas.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(ReservasDbContext))]
    [Migration("20260808133410_TurnosServicio")]
    partial class TurnosServicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reservas")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Reservas.Dominio.AgendaCalendario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_agenda_empresa");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_agenda_token");

                    b.ToTable("agenda_calendario", "reservas");
                });

            modelBuilder.Entity("AlxorCore.Reservas.Dominio.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<Guid?>("ComandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comanda_id");

                    b.Property<int>("Comensales")
                        .HasColumnType("integer")
                        .HasColumnName("comensales");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<Guid?>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<string>("Telefono")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "FechaHora")
                        .HasDatabaseName("ix_reserva_empresa_fecha");

                    b.ToTable("reserva", "reservas");
                });

            modelBuilder.Entity("AlxorCore.Reservas.Dominio.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("AforoComensales")
                        .HasColumnType("integer")
                        .HasColumnName("aforo_comensales");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Dias")
                        .HasColumnType("integer")
                        .HasColumnName("dias");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Activo")
                        .HasDatabaseName("ix_turno_empresa_activo");

                    b.ToTable("turno", "reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
