<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>AlxorCore.Api</RootNamespace>
    <AssemblyName>AlxorCore.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
    <ProjectReference Include="..\AlxorCore.Identidad\AlxorCore.Identidad.csproj" />
    <ProjectReference Include="..\AlxorCore.Identidad.Infraestructura\AlxorCore.Identidad.Infraestructura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

</Project>
