<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AlxorCore.Organizacion</RootNamespace>
    <AssemblyName>AlxorCore.Organizacion</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlxorCore.Nucleo\AlxorCore.Nucleo.csproj" />
  </ItemGroup>

</Project>
