// <auto-generated />
using System;
using AlxorCore.Hosteleria.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Hosteleria.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(HosteleriaDbContext))]
    [Migration("20260817194410_LineaComandaCobroParcial")]
    partial class LineaComandaCobroParcial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hosteleria")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbiertaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("abierta_en");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<string>("MetodoCobro")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_cobro");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroTicket")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_ticket");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado", "MesaId")
                        .HasDatabaseName("ix_comanda_empresa_estado_mesa");

                    b.ToTable("comanda", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_y");

                    b.Property<string>("Zona")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .HasDatabaseName("ix_mesa_empresa_nombre");

                    b.ToTable("mesa", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.Comanda", b =>
                {
                    b.OwnsMany("AlxorCore.Hosteleria.Dominio.LineaComanda", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Base")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("base");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<decimal>("CantidadCobrada")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_cobrada");

                            b1.Property<decimal>("CantidadEnviadaCocina")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_enviada_cocina");

                            b1.Property<string>("CodigoIva")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("codigo_iva");

                            b1.Property<Guid>("ComandaId")
                                .HasColumnType("uuid")
                                .HasColumnName("comanda_id");

                            b1.Property<decimal>("CuotaIva")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("cuota_iva");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<decimal>("PorcentajeIva")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_iva");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("precio_unitario");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ComandaId")
                                .HasDatabaseName("ix_linea_comanda_comanda");

                            b1.ToTable("linea_comanda", "hosteleria");

                            b1.WithOwner()
                                .HasForeignKey("ComandaId");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
