// <auto-generated />
using System;
using AlxorCore.Hosteleria.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlxorCore.Hosteleria.Infraestructura.Persistencia.Migraciones
{
    [DbContext(typeof(HosteleriaDbContext))]
    [Migration("20261010111223_OpcionesProducto")]
    partial class OpcionesProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hosteleria")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.AvisoMesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AtendidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atendido_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<DateTimeOffset>("RecibidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recibido_en");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "AtendidoEn")
                        .HasDatabaseName("ix_aviso_mesa_empresa_atendido");

                    b.ToTable("aviso_mesa", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AbiertaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("abierta_en");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("base_imponible");

                    b.Property<DateTimeOffset?>("CerradaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cerrada_en");

                    b.Property<decimal>("CuotaIva")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("cuota_iva");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid?>("FacturaId")
                        .HasColumnType("uuid")
                        .HasColumnName("factura_id");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<string>("MetodoCobro")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("metodo_cobro");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas");

                    b.Property<string>("NumeroTicket")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("numero_ticket");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("usuario_nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado", "MesaId")
                        .HasDatabaseName("ix_comanda_empresa_estado_mesa");

                    b.ToTable("comanda", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.ConfiguracionCarta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tema");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_configuracion_carta_empresa");

                    b.ToTable("configuracion_carta", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.FichaCarta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<bool>("Agotado")
                        .HasColumnType("boolean")
                        .HasColumnName("agotado");

                    b.Property<int>("Alergenos")
                        .HasColumnType("integer")
                        .HasColumnName("alergenos");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("bytea")
                        .HasColumnName("foto");

                    b.Property<string>("FotoTipo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("foto_tipo");

                    b.Property<bool>("Picante")
                        .HasColumnType("boolean")
                        .HasColumnName("picante");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<bool>("Recomendado")
                        .HasColumnType("boolean")
                        .HasColumnName("recomendado");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId")
                        .IsUnique()
                        .HasDatabaseName("ux_ficha_carta_producto");

                    b.ToTable("ficha_carta", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.GrupoOpcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obligatorio");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_id");

                    b.Property<string>("Seleccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("seleccion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "ProductoId")
                        .HasDatabaseName("ix_grupo_opcion_producto");

                    b.ToTable("grupo_opcion", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.MenuDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Incluye")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("incluye");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_menu_dia_empresa");

                    b.ToTable("menu_dia", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean")
                        .HasColumnName("activa");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer")
                        .HasColumnName("capacidad");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre");

                    b.Property<double>("PosX")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_x");

                    b.Property<double>("PosY")
                        .HasColumnType("double precision")
                        .HasColumnName("pos_y");

                    b.Property<Guid>("TokenCarta")
                        .HasColumnType("uuid")
                        .HasColumnName("token_carta");

                    b.Property<string>("Zona")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("zona");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .HasDatabaseName("ix_mesa_empresa_nombre");

                    b.ToTable("mesa", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("concepto");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("importe");

                    b.Property<DateTimeOffset>("Momento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("momento");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("UsuarioNombre")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("usuario_nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Fecha")
                        .HasDatabaseName("ix_caja_movimiento_empresa_fecha");

                    b.ToTable("caja_movimiento", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.PedidoWeb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ComandaId")
                        .HasColumnType("uuid")
                        .HasColumnName("comanda_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("idioma");

                    b.Property<Guid>("MesaId")
                        .HasColumnType("uuid")
                        .HasColumnName("mesa_id");

                    b.Property<DateTimeOffset>("RecibidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recibido_en");

                    b.Property<DateTimeOffset?>("ResueltoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resuelto_en");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Estado", "RecibidoEn")
                        .HasDatabaseName("ix_pedido_web_empresa_estado");

                    b.ToTable("pedido_web", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.SuscripcionBar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ux_suscripcion_empresa");

                    b.ToTable("suscripcion", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.TraduccionCarta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ActualizadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizada_en");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ambito");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("clave");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("idioma");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Ambito", "Clave", "Idioma")
                        .IsUnique()
                        .HasDatabaseName("ux_traduccion_carta");

                    b.ToTable("traduccion_carta", "hosteleria");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.Comanda", b =>
                {
                    b.OwnsMany("AlxorCore.Hosteleria.Dominio.LineaComanda", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Base")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("base");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<decimal>("CantidadCobrada")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_cobrada");

                            b1.Property<decimal>("CantidadEnviadaCocina")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad_enviada_cocina");

                            b1.Property<string>("CodigoIva")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("codigo_iva");

                            b1.Property<Guid>("ComandaId")
                                .HasColumnType("uuid")
                                .HasColumnName("comanda_id");

                            b1.Property<decimal>("CuotaIva")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("cuota_iva");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<string>("Nota")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nota");

                            b1.Property<decimal>("PorcentajeIva")
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("porcentaje_iva");

                            b1.Property<decimal>("PrecioUnitario")
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("precio_unitario");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.HasKey("Id");

                            b1.HasIndex("ComandaId")
                                .HasDatabaseName("ix_linea_comanda_comanda");

                            b1.ToTable("linea_comanda", "hosteleria");

                            b1.WithOwner()
                                .HasForeignKey("ComandaId");
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.GrupoOpcion", b =>
                {
                    b.OwnsMany("AlxorCore.Hosteleria.Dominio.OpcionProducto", "Opciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<Guid>("GrupoOpcionId")
                                .HasColumnType("uuid")
                                .HasColumnName("grupo_opcion_id");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)")
                                .HasColumnName("nombre");

                            b1.Property<int>("Orden")
                                .HasColumnType("integer")
                                .HasColumnName("orden");

                            b1.Property<decimal>("PrecioDelta")
                                .HasColumnType("numeric(14,2)")
                                .HasColumnName("precio_delta");

                            b1.HasKey("Id");

                            b1.HasIndex("GrupoOpcionId")
                                .HasDatabaseName("ix_opcion_producto_grupo");

                            b1.ToTable("opcion_producto", "hosteleria");

                            b1.WithOwner()
                                .HasForeignKey("GrupoOpcionId");
                        });

                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.MenuDia", b =>
                {
                    b.OwnsMany("AlxorCore.Hosteleria.Dominio.PlatoMenu", "Platos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<Guid>("MenuDiaId")
                                .HasColumnType("uuid")
                                .HasColumnName("menu_dia_id");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(160)
                                .HasColumnType("character varying(160)")
                                .HasColumnName("nombre");

                            b1.Property<int>("Orden")
                                .HasColumnType("integer")
                                .HasColumnName("orden");

                            b1.Property<string>("Seccion")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("seccion");

                            b1.HasKey("Id");

                            b1.HasIndex("MenuDiaId")
                                .HasDatabaseName("ix_menu_dia_plato_menu");

                            b1.ToTable("menu_dia_plato", "hosteleria");

                            b1.WithOwner()
                                .HasForeignKey("MenuDiaId");
                        });

                    b.Navigation("Platos");
                });

            modelBuilder.Entity("AlxorCore.Hosteleria.Dominio.PedidoWeb", b =>
                {
                    b.OwnsMany("AlxorCore.Hosteleria.Dominio.LineaPedidoWeb", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Cantidad")
                                .HasColumnType("numeric(14,3)")
                                .HasColumnName("cantidad");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("descripcion");

                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("empresa_id");

                            b1.Property<string>("Nota")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("nota");

                            b1.Property<Guid>("PedidoWebId")
                                .HasColumnType("uuid")
                                .HasColumnName("pedido_web_id");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uuid")
                                .HasColumnName("producto_id");

                            b1.HasKey("Id");

                            b1.HasIndex("PedidoWebId")
                                .HasDatabaseName("ix_linea_pedido_web_pedido");

                            b1.ToTable("linea_pedido_web", "hosteleria");

                            b1.WithOwner()
                                .HasForeignKey("PedidoWebId");
                        });

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
